services:
  app:
    image: whoami-curl:latest
    networks:
      - traefik-network
    labels:
      - "traefik.http.routers.${STACK_NAME}_app.rule=Host(`${STACK_NAME}.localhost`)"
      - "traefik.http.services.${STACK_NAME}_app.loadbalancer.server.port=80"

    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 5s
        order: start-first
      restart_policy:
        condition: on-failure

networks:
  traefik-network:
    external: true