services:
  app:
    image: whoami-curl:latest
    networks:
      - traefik-network
    labels:
      - "traefik.http.routers.${SERVICE_NAME}.rule=Host(`${SERVICE_NAME}.localhost`)"
      - "traefik.http.services.${SERVICE_NAME}.loadbalancer.server.port=80"
    health_check:

    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 5s
        order: start-first
      restart_policy:
        condition: on-failure

networks:
  traefik-network:
    external: true